### ISSUE TITLE
Clear separation of concerns between Binary Proxy and Court

### ISSUE THREAD

**Issue by marsrobertson** [kleros/arbitrable-proxy-contracts#3]
These two are overlapping.

**Binary Proxy**

- Creating a dispute
- View on court
- Submit evidence
- No way to view primary document 

**Court**

- View primary document
- No way to submit evidence

---

A suggested way:

**Binary Proxy** - dispute creation only - all the rest in the court

**Court** - add the ability to submit evidence.

**Comment by ferittuncer** [comment]
The suggested way is not possible to implement because evidence submission functionality is on an arbitrable contract. But the Court is an arbitrator.
